In [1]:
from einops import rearrange, repeat, reduce

In [2]:
import torch

In [3]:
from wasserstein import wasserstein_dist

In [4]:
mean = torch.ones((2,2,4))
log_var = torch.randint(3, (2, 2, 4)).to(torch.float32)

In [5]:
mean.requires_grad=True
log_var.requires_grad=True

In [6]:
log_var

tensor([[[1., 2., 1., 0.],
         [0., 0., 2., 0.]],

        [[0., 0., 0., 2.],
         [1., 2., 2., 1.]]], requires_grad=True)

In [7]:
dist = wasserstein_dist(mean, log_var)

In [8]:
loss = torch.sum(dist)

In [9]:
loss.backward()

In [10]:
mean

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]], requires_grad=True)

In [11]:
mean.grad

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
log_var.grad

tensor([[[ 0.2674,  0.4409,  0.2674,  0.1622],
         [-0.3770, -0.3770, -1.0247, -0.3770]],

        [[-0.1622, -0.1622, -0.1622, -0.4409],
         [ 0.6215,  1.0247,  1.0247,  0.6215]]])

In [13]:
log_var.shape

torch.Size([2, 2, 4])

In [14]:
log_var_mean = reduce(log_var, 'b h d -> b h', reduction='mean')

In [22]:
co_var = torch.matmul(rearrange(log_var_mean, 'b h -> b h 1'),rearrange(log_var_mean, 'b h -> b 1 h'))

In [15]:
dist.shape

torch.Size([2, 2])

In [27]:
torch.diagonal(co_var, dim1=-2, dim2=-1).shape

torch.Size([2, 2])

In [14]:
dist

tensor([[0.0000, 0.6736],
        [0.6736, 0.0000]], grad_fn=<AsStridedBackward>)